Resources:
  SystemIntegrationPolicy6FA12ED7:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: iam:*
            Effect: Allow
            Resource: "*"
            Sid: AllowIAM
        Version: "2012-10-17"
      Description: ""
      Path: /
    Metadata:
      aws:cdk:path: SimulationStack/SystemIntegrationPolicy/Resource
  CredentialExposure2C2BE0C1:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns:
        - Ref: SystemIntegrationPolicy6FA12ED7
      UserName: integration
    Metadata:
      aws:cdk:path: SimulationStack/CredentialExposure/Resource
  CredentialExposureAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: CredentialExposure2C2BE0C1
      Status: Active
    Metadata:
      aws:cdk:path: SimulationStack/CredentialExposureAccessKey
  CryptoMiningPolicyD641E830:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: ec2:*
            Effect: Allow
            Resource: "*"
            Sid: AllowEC2
        Version: "2012-10-17"
      Description: ""
      Path: /
    Metadata:
      aws:cdk:path: SimulationStack/CryptoMiningPolicy/Resource
  CryptoMiningCredentialF9F78A67:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns:
        - Ref: CryptoMiningPolicyD641E830
      UserName: pipeline
    Metadata:
      aws:cdk:path: SimulationStack/CryptoMiningCredential/Resource
  CryptoMiningAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: CryptoMiningCredentialF9F78A67
      Status: Active
    Metadata:
      aws:cdk:path: SimulationStack/CryptoMiningAccessKey
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAE1WMwQrCMBBEv6X3dGvVg0elRxFLxQ8I21XX2kSyGySU/rsG8eDpDW+GqaGu17AotvYlJfZDNaEPBNNJLQ6mubhj1GdU03gnGiJqdh2JjwEp50/Rs7J3s8kXbEeYDtbZK/WtfzCmPPoXZ6GQ7Y87RBLZU5pn0ya9eVetYAPL4i7MZYhOeSTovnwD0tac7LEAAAA=
    Metadata:
      aws:cdk:path: SimulationStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  CredentialExposureAccessKeySecret:
    Description: IAM user access key secret for exposed credential scenario
    Value:
      Fn::GetAtt:
        - CredentialExposureAccessKey
        - SecretAccessKey
  CredentialExposureAccessKeyId:
    Description: IAM user access key id for exposed credential scenario
    Value:
      Ref: CredentialExposureAccessKey
  CryptoMiningAccessKeySecret:
    Description: IAM user access key secret for crypto mining scenario
    Value:
      Fn::GetAtt:
        - CryptoMiningAccessKey
        - SecretAccessKey
  CryptoMiningAccessKeyId:
    Description: IAM user access key id for crypto mining scenario
    Value:
      Ref: CryptoMiningAccessKey
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

